### ISSUE TITLE
Banka Listelerini json olarak nasıl çekebilirim?

### ISSUE THREAD

**Issue by NTMS2017** [emnsen/bankalar#2]
Banka Listelerini json olarak nasıl çekebilirim? teşekkürler

**Comment by emnsen** [comment]
json olarak dosya mevcut repoyu clonelayıp veya indirerek içerisindeki bankalar.json dosyasını kullandığınız dilde dosya okuma ve json parse yaparak çekebilirsiniz.

**Comment by NTMS2017** [comment]
Teşekkürler,
